### ISSUE TITLE
Doesn't work with nrwl/nx-console in VS code

### ISSUE THREAD

**Issue by vladimirdrayling** [co-IT/ngrx-ducks#39] opened 2020-08-27 14:52 UTC
After installation of `@ngrx-ducks/core` the nx console stoped working in VS code.

### Reproduction steps

0. `npx create-nx-workspace some-workspace --preset=angular --cli=angular --style=scss --nx-cloud=false`.
0. ` yarn add @ngrx-ducks/core`.
0. Start VS code (stable/insiders) install `nx console` extension.
0. Click on installed extension in the sidebar.
0. Click on generate. At this point nothing happens.

![image](https://user-images.githubusercontent.com/16114644/91457692-edbaf080-e884-11ea-8ea6-8d0e4fc79949.png)

Hope the solution will be released in the future.

**Comment by GregOnNet** [comment] 2020-08-28 05:17
Hi,

thanks for reporting this issue.
I can reproduce it and started asking for a helping hand since I do not know how to start investigating this isse.

**Comment by isaacplmann** [comment] 2020-08-28 18:39
The problem is this line: https://github.com/co-IT/ngrx-ducks/blob/master/packages/core/package.json#L26

Nx console (and the angular cli) looks for a file at that location and since it doesn't exist nx console dies.  I'll fix that issue on the nx console side, but you should delete that line if you don't have any schematics.

**Comment by isaacplmann** [comment] 2020-08-28 19:22
https://github.com/nrwl/nx-console/pull/971

Here's the PR that fixes this from the nx-console side.

**Comment by GregOnNet** [comment] 2020-08-29 07:10
Hi @isaacplmann,

thanks for the quick help.
I also thought it is this reference as I told Juri before.

Currently, the schematics are a peer-dependency.
Maybe I should set it as a real dependency. 🤔

Thanks again.

Cheers
Gregor

**Comment by GregOnNet** [comment] 2020-08-29 07:10
Closing this issue due to a fix that will be provided by *nx-console*.

**Closed by GregOnNet** 2020-08-29 07:10 UTC
Labels: bug, help wanted
